# Generated by Django 3.0.5 on 2020-04-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_patient',
        ),
    ]
