# Generated by Django 3.0.2 on 2020-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthya', '0003_auto_20200412_1819'),
        ('swasthya', '0003_doctor_location'),
    ]

    operations = [
    ]
