# Generated by Django 3.0.5 on 2020-04-18 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swasthya', '0004_merge_20200415_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Record', max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('record', models.ImageField(default='images/no-img.png', upload_to='images/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swasthya.Patient')),
            ],
        ),
    ]
