# Generated by Django 3.0.2 on 2020-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthya', '0007_auto_20200418_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
